# Generated by Django 4.2.5 on 2023-11-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_assigned_task_assigneddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskName',
            new_name='taskTitle',
        ),
    ]
