# Generated by Django 4.2.5 on 2023-11-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_taskname_task_tasktitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='projectTitle',
        ),
    ]
