# Generated by Django 4.2.5 on 2023-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_project_managername_project_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='managerName',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
