# Generated by Django 4.2.5 on 2023-11-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_project_manager_remove_project_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='ManagerEmail',
            new_name='managerEmail',
        ),
    ]
