# Generated by Django 4.2.5 on 2023-11-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_manageremail_project_manageremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectTitle',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
