# Generated by Django 4.2.5 on 2023-11-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_project_projecttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectTitle',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
