# Generated by Django 4.2.5 on 2023-11-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_project_projecttitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managerEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
