# Generated by Django 4.2.5 on 2023-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_project_manageremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectTitle',
            field=models.CharField(max_length=64),
        ),
    ]
