# Generated by Django 4.2.5 on 2023-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_project_owneremail_project_ownername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ManagerEmail',
            new_name='managerEmail',
        ),
        migrations.AddField(
            model_name='project',
            name='taskIDs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='dashboard.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='managerName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
