# Generated by Django 4.2.7 on 2023-11-26 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_manageremail_task_manageremail_project_tasks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('chatID', models.SlugField(max_length=15, primary_key=True, serialize=False)),
                ('prevMessage', models.CharField(blank=True, max_length=15)),
                ('text', models.TextField()),
                ('senderName', models.CharField(blank=True, max_length=30)),
                ('senderEmail', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('E', 'Employee'), ('M', 'Manager'), ('O', 'Owner')], default='E', max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='EmployeeName',
            new_name='employeeName',
        ),
        migrations.RemoveField(
            model_name='task',
            name='EmployeeEmail',
        ),
        migrations.AddField(
            model_name='project',
            name='chat',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='managerEmail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='employeeEmail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
