# Generated by Django 4.2.5 on 2023-11-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rename_manageremail_task_manageremail_project_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tasks',
            new_name='taskIDs',
        ),
    ]
