# Generated by Django 4.2.5 on 2023-12-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_message_rename_employeename_task_employeename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='decline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='late',
            field=models.BooleanField(default=False),
        ),
    ]
