# Generated by Django 4.2.7 on 2023-11-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_tasks_project_taskids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='late',
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
