# Generated by Django 4.2.7 on 2023-11-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_tasks_project_taskids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='EmployeeEmail',
            new_name='employeeEmail',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='EmployeeName',
            new_name='employeeName',
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
