# Generated by Django 4.2.7 on 2023-11-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_task_late_alter_task_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('chatID', models.SlugField(max_length=15, primary_key=True, serialize=False)),
                ('prevMessage', models.CharField(blank=True, max_length=15)),
                ('text', models.TextField()),
                ('senderName', models.CharField(blank=True, max_length=30)),
                ('senderEmail', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('E', 'Employee'), ('M', 'Manager'), ('O', 'Owner')], default='E', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='chat',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
