# Generated by Django 4.2.7 on 2023-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_employeeemail_task_employeeemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='submitted',
            field=models.DateTimeField(blank=True),
        ),
    ]
