# Generated by Django 4.2.7 on 2023-11-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_task_completed_alter_task_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='employeeEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
