# Generated by Django 4.2.7 on 2023-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_task_employeeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='managerEmail',
            field=models.EmailField(max_length=254),
        ),
    ]
