# Generated by Django 4.2.5 on 2023-11-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_message_project_chat'),
        ('dashboard', '0023_alter_task_manageremail'),
    ]

    operations = [
    ]
