# Generated by Django 4.2.5 on 2023-10-03 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_employee_options_alter_manager_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='company_details',
        ),
    ]
