# Generated by Django 4.2.5 on 2023-11-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to='accounts.manager'),
        ),
    ]
