# Generated by Django 4.2.5 on 2023-11-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_owner_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='managers',
        ),
    ]
