# Generated by Django 4.2.5 on 2023-12-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_contact'),
        ('accounts', '0014_remove_owner_managers'),
    ]

    operations = [
    ]
